# Generated by Django 5.2.11 on 2026-03-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[("member", "Member"), ("cio", "CIO")],
                max_length=10,
                null=True,
            ),
        ),
    ]
