# Generated by Django 5.2.11 on 2026-03-30 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_merge_0005_event_0006_profile_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cio',
            name='status',
            field=models.CharField(choices=[('public', 'Public'), ('hidden', 'Hidden')], default='hidden', max_length=20),
        ),
    ]
