# Generated by Django 5.2.11 on 2026-04-13 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_event_attendees_event_created_at_event_host_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cio',
            name='image_url',
        ),
        migrations.AddField(
            model_name='cio',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='cio_pictures/'),
        ),
    ]
