# Generated by Django 5.2.11 on 2026-04-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_alter_profile_role_ciorequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciorequest',
            name='application_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]