# Generated by Django 5.2.11 on 2026-04-16 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("profiles", "0015_notification"),
	]

	operations = [
		migrations.AddField(
			model_name="event",
			name="is_promoted",
			field=models.BooleanField(default=False),
		),
		migrations.AddField(
			model_name="event",
			name="promoted_at",
			field=models.DateTimeField(blank=True, null=True),
		),
		migrations.AddField(
			model_name="notification",
			name="event",
			field=models.ForeignKey(
				blank=True,
				null=True,
				on_delete=django.db.models.deletion.CASCADE,
				related_name="notifications",
				to="profiles.event",
			),
		),
	]
