# Generated by Django 5.2.11 on 2026-04-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0016_event_promotion_notification_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[("message", "Message"), ("event_reminder", "Event Reminder")],
                default="message",
                max_length=20,
            ),
        ),
    ]
